# Generated by Django 2.2.6 on 2021-07-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210707_1700'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_list',
        ),
    ]
