# Generated by Django 2.2.6 on 2021-08-31 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210831_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='user',
        ),
    ]
